# 开发环境配置
server:
  port: 8882

# Spring配置
spring:
  # 数据库连接
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: wiki
    password: wiki
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=UTF8&autoReconnect=true&useSSL=false

# MyBatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml

# 日志配置 trace最低等级
logging:
  level:
    com:
      pdd:
        wiki:
          mapper: trace


